### PR TITLE
fix: back to the original function

### LINKED ISSUE #525: bug: restore "Registered" status for Serialized Parts lifecycle
### Current Behavior
After the changes introduced in PR https://github.com/eclipse-tractusx/industry-core-hub/pull/521, the **Registered** status for Serialized Parts is no longer visible in the UI.

Currently, Serialized Parts only appear with the **Shared** state. This affects several parts of the application where Serialized Parts are displayed or managed.

As a result, the **Registered** stage of the lifecycle is no longer represented, and the distinction between **Registered** and **Shared** has effectively disappeared.

### Expected Behavior
Serialized Parts should have **two lifecycle states visible again**:

- **Registered**
- **Shared**

The **Registered** state should be displayed before a Serialized Part becomes **Shared**, restoring the original lifecycle behavior.

This should apply consistently in:
- Catalog Part details
- Serialized Parts screen
- Eco Pass KIT Passport Provisioning process

Restoring the **Registered** status ensures the lifecycle stages are properly represented and aligns with the original behavior before PR #521.

### Steps To Reproduce
1. Open the application.
2. Navigate to any of the following screens:
   - Catalog Part details
   - Serialized Parts page
   - Eco Pass KIT Passport Provisioning process
3. Observe the lifecycle status of Serialized Parts.

**Observed result:**  
Serialized Parts do not show the **Registered** status anymore and appear only as **Shared**.

**Expected result:**  
Serialized Parts should display **Registered** before transitioning to **Shared**, restoring the previous lifecycle flow.

### PR DESCRIPTION
**Pull request by jalvaro-lks**
## WHAT

Restores the **Registered** intermediate status for Serialized Parts, reverting the changes introduced in [PR #521](https://github.com/eclipse-tractusx/industry-core-hub/pull/521) that merged Registration and Sharing into a single step. The status flow is now **Draft → Registered → Shared** again, with distinct actions and icons for each transition.

## WHY

[PR #521](https://github.com/eclipse-tractusx/industry-core-hub/pull/521) removed the Registered state assuming that registration already made twins visible to partners, collapsing the flow into Draft → Shared. This removed a useful intermediate state that allows users to register a twin in the DTR without immediately sharing it via TwinExchange, giving more control over the data sharing lifecycle.

Closes #525

### CODE REVIEW

File: ichub-frontend/src/features/industry-core-kit/serialized-parts/components/SerializedPartsTable.tsx [hunk 1]
```diff
@@ -262,26 +267,14 @@ const SerializedPartsTable = ({ parts, onRefresh }: SerializedPartsTableProps) =
...
-      try {
-        await shareSerializedPartTwin({
-          manufacturerId: row.manufacturerId,
-          manufacturerPartId: row.manufacturerPartId,
-          partInstanceId: row.partInstanceId,
-        });
-      } catch (shareErr) {
-        // Share may fail if TwinExchange already exists — not critical since DTR visibility is already set
-        console.warn('Auto-share after registration warning:', shareErr);
-      }
```
Comment (matbmoser) [inline ichub-frontend/src/features/industry-core-kit/serialized-parts/components/SerializedPartsTable.tsx:282]: But are we doing this also when we call the "share" of the passport.

**Comment by matbmoser** [comment]
I will merge into my final branch.
